// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/skkm/skkm.proto

package go_micro_srv_skkm

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Skkm service

type SkkmService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Skkm_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Skkm_PingPongService, error)
}

type skkmService struct {
	c    client.Client
	name string
}

func NewSkkmService(name string, c client.Client) SkkmService {
	return &skkmService{
		c:    c,
		name: name,
	}
}

func (c *skkmService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Skkm.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skkmService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Skkm_StreamService, error) {
	req := c.c.NewRequest(c.name, "Skkm.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &skkmServiceStream{stream}, nil
}

type Skkm_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type skkmServiceStream struct {
	stream client.Stream
}

func (x *skkmServiceStream) Close() error {
	return x.stream.Close()
}

func (x *skkmServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *skkmServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *skkmServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *skkmServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *skkmService) PingPong(ctx context.Context, opts ...client.CallOption) (Skkm_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Skkm.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &skkmServicePingPong{stream}, nil
}

type Skkm_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type skkmServicePingPong struct {
	stream client.Stream
}

func (x *skkmServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *skkmServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *skkmServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *skkmServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *skkmServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *skkmServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Skkm service

type SkkmHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Skkm_StreamStream) error
	PingPong(context.Context, Skkm_PingPongStream) error
}

func RegisterSkkmHandler(s server.Server, hdlr SkkmHandler, opts ...server.HandlerOption) error {
	type skkm interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Skkm struct {
		skkm
	}
	h := &skkmHandler{hdlr}
	return s.Handle(s.NewHandler(&Skkm{h}, opts...))
}

type skkmHandler struct {
	SkkmHandler
}

func (h *skkmHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.SkkmHandler.Call(ctx, in, out)
}

func (h *skkmHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.SkkmHandler.Stream(ctx, m, &skkmStreamStream{stream})
}

type Skkm_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type skkmStreamStream struct {
	stream server.Stream
}

func (x *skkmStreamStream) Close() error {
	return x.stream.Close()
}

func (x *skkmStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *skkmStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *skkmStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *skkmStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *skkmHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.SkkmHandler.PingPong(ctx, &skkmPingPongStream{stream})
}

type Skkm_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type skkmPingPongStream struct {
	stream server.Stream
}

func (x *skkmPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *skkmPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *skkmPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *skkmPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *skkmPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *skkmPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
